export { default as Home } from './home'
export { default as User } from './user'
export { default as Common } from './common'
export { default as Detail } from './detail'
export { default as Cart } from './cart'
export { default as Category } from './category'